---
title: "Practicing Mapping"
author: "Abby Bergman"
date: "11/14/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load packages
library(tidyverse)
library(ggmap)
library(RColorBrewer)
library(gridExtra)
library(fiftystater)
library(rscorecard)
library(knitr)
library(dplyr)
library(dbplyr)
library(RSQLite)
library(sf)
library(viridis)
```

```{r}
#USA data
data("fifty_states")
as_tibble(fifty_states) 

#make simple feature
st_as_sf(fifty_states, coords = c("long", "lat"))%>% 
  
  # convert fifty_states to an sf data frame
  (sf_fifty <- st_as_sf(fifty_states, coords = c("long", "lat")) %>% 
     # convert sets of points to polygons
     group_by(id, piece) %>% 
     summarize(do_union = FALSE) %>%
     st_cast("POLYGON") %>%
     # convert polygons to multipolygons for states with discontinuous regions
     group_by(id) %>%
     summarize())

ggplot(data = sf_fifty) +
  geom_sf()
```
```{r}
#setting up scorecard data
library(rscorecard)

 
```


```{r}
#import usa
usa <- st_read("data/census_bureau/cb_2013_us_state_20m/cb_2013_us_state_20m.shp")

#import school data
schools_by_state <- read_csv("/Users/AbigailBergman/Desktop/Grad School/Fall Quarter 2018/Computing/Homework/hw7/schools_by_state.csv")

population <- read_csv("/Users/AbigailBergman/Desktop/Grad School/Fall Quarter 2018/Computing/Homework/hw7/population.csv")


# convert fifty_states to an sf data frame
(sf_fifty <- st_as_sf(fifty_states, coords = c("long", "lat")) %>% 
   # convert sets of points to polygons
   group_by(id, piece) %>% 
   summarize(do_union = FALSE) %>%
   st_cast("POLYGON") %>%
   # convert polygons to multipolygons for states with discontinuous regions
   group_by(id) %>%
   summarize())

#need to do left join
combined1 <-left_join(schools_by_state %>% mutate(id = tolower(id)), sf_fifty, by = "id")

combined <-left_join(combined1, population %>% mutate(id = tolower(id)), by = "id")

combined <- combined %>%
  mutate(per_capita = total/`2018 Population`)

#graph

ggplot(data = combined) +
  geom_sf(aes(fill = per_capita))

ggplot(data = combined1)+
  geom_sf(aes(fill = total)) + 
  labs(title = "Map of USA, Number of Colleges by State")

#bin data
combined %>%
  mutate(capita_cut = cut_number(per_capita, 4))%>%
  ggplot() +
  geom_sf(aes(fill = capita_cut)) +
  labs(title = "Number of Universities", 
       subtitle = "Divided by State Population") +
  guides(fill=guide_legend(title="Number of Universities Per Person"))

viridis_base <- combined1 %>%
  mutate(total_cut = cut_number(total, 4))%>%
  ggplot() +
  geom_sf(aes(fill = total_cut)) +
  labs(title = "Number of Universities in each State") + 
  guides(fill=guide_legend(title="Number of Universities")) +
  scale_color_viridis(option ="cividis", labels = scales::dollar)


display.brewer.all(type = "div")
```


```{r}
#importing college data

col_shape <- st_read("/Users/AbigailBergman/Desktop/Grad School/Fall Quarter 2018/Computing/Homework/hw7/CollegesUniversities/CollegesUniversities.shp")

ggplot(data = col_shape) +
  geom_sf()

```
